services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: single_tenant_pos
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  db-test:
    image: postgres:13
    environment:
      POSTGRES_DB: single_tenant_pos_test
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    ports:
      - "55433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  postgres_data_test:
